version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./backend-php:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - mysql

  symfony:
    build:
      context: ./docker/symfony
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - ./backend-symfony:/var/www/symfony
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  vue:
    build:
      context: ./frontend-vue   # Upewnij się, że kontekst to jest frontend-vue
      dockerfile: ../docker/vue/Dockerfile  # Wskażemy poprawną lokalizację Dockerfile
    container_name: vue_frontend
    volumes:
      - ./frontend-vue:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - php
      - symfony
